/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/7lTRS3Y8Luw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function IntialPage() {
  return (
    <div className="flex justify-center items-center min-h-screen bg-gray-100">
      <div className="flex flex-col md:flex-row bg-white p-8 rounded-lg shadow-lg max-w-4xl mx-auto">
        <div className="md:w-1/2">
          <img
            alt="Astronauts playing chess"
            className="block mx-auto"
            height="400"
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/400",
              objectFit: "cover",
            }}
            width="400"
          />
        </div>
        <div className="flex flex-col space-y-6 md:w-1/2 mt-6 md:mt-0 md:ml-8">
          <h1 className="text-3xl font-bold text-center md:text-left text-black">Guess the prompt</h1>
          <p className="text-lg text-center md:text-left text-black">Can you guess the prompt used to generate this image?</p>
          <div className="flex flex-col space-y-4">
            <Textarea placeholder="Guess the prompt used to generate the image" />
            <Button>Submit</Button>
          </div>
        </div>
      </div>
    </div>
  )
}
