/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rqXMDuA46Tz
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export function IntialScreen() {
  return (
    <div className="flex h-screen w-full items-center justify-center bg-white p-8">
      <div className="flex flex-col items-center justify-center w-full max-w-4xl p-8">
        <h1 className="text-3xl font-bold text-center text-black">Guess the prompt</h1>
        <p className="mt-2 text-sm text-gray-600 text-center">Can you guess the prompt used to generate this image?</p>
        <div className="flex flex-col lg:flex-row items-center justify-between w-full mt-8">
          <div className="w-full lg:w-1/2">
            <img
              alt="Guess the prompt illustration"
              className="mt-4 h-[400px] w-[400px] lg:ml-0 lg:mr-4"
              height="400"
              src="/placeholder.svg"
              style={{
                aspectRatio: "400/400",
                objectFit: "cover",
              }}
              width="400"
            />
          </div>
          <div className="w-full lg:w-1/2">
            <div className="w-full max-w-md rounded-md bg-white p-4 shadow-md mb-4">
              <label className="sr-only" htmlFor="guess">
                Guess the prompt used to generate the image
              </label>
              <textarea
                className="mt-1 w-full rounded-md border-gray-300 p-2 text-sm shadow-sm"
                id="guess"
                placeholder="Guess the prompt used to generate the image"
                rows="4"
              />
            </div>
            <Button className="w-full max-w-md">Submit</Button>
          </div>
        </div>
      </div>
    </div>
  )
}
