/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/hOToE3phMlK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function LoadingScreen() {
  return (
    <div className="flex h-screen w-full items-center justify-center bg-white">
      <div className="mx-auto flex max-w-4xl flex-col items-center px-4">
        <h1 className="text-3xl font-bold text-black">Guess the prompt</h1>
        <p className="mt-2 text-lg text-black">Can you guess the prompt used to generate this image?</p>
        <div className="mt-8 flex w-full justify-between space-x-8">
          <div className="w-[600px]">
            <img
              alt="Generated image"
              className="h-[400px] w-full object-cover rounded-lg"
              height="400"
              src="/placeholder.svg"
              style={{
                aspectRatio: "600/400",
                objectFit: "cover",
              }}
              width="600"
            />
          </div>
          <div className="flex h-[400px] w-[600px] items-center justify-center rounded-lg bg-gray-100">
            <LoaderIcon className="text-4xl text-gray-400" />
          </div>
        </div>
      </div>
    </div>
  )
}

function LoaderIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="6" />
      <line x1="12" x2="12" y1="18" y2="22" />
      <line x1="4.93" x2="7.76" y1="4.93" y2="7.76" />
      <line x1="16.24" x2="19.07" y1="16.24" y2="19.07" />
      <line x1="2" x2="6" y1="12" y2="12" />
      <line x1="18" x2="22" y1="12" y2="12" />
      <line x1="4.93" x2="7.76" y1="19.07" y2="16.24" />
      <line x1="16.24" x2="19.07" y1="7.76" y2="4.93" />
    </svg>
  )
}
