/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/T0gnsfNJpNN
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export function ScoreScreen() {
  return (
    <div className="bg-white p-8">
      <h1 className="text-3xl font-bold text-center mb-6 text-black">Guess the prompt</h1>
      <p className="text-center text-lg mb-12 text-black">Can you guess the prompt used to generate this image?</p>
      <div className="flex justify-center gap-8 mb-8">
        <div className="max-w-sm">
          <img
            alt="Original illustration"
            className="rounded-lg mb-4"
            height="300"
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width="400"
          />
          <h2 className="text-lg font-semibold mb-2 text-black">Original prompt</h2>
          <p className="text-black no-margin">Create a unique illustration of two astronauts playing chess in space.</p>
        </div>
        <div className="max-w-sm">
          <img
            alt="Your guess"
            className="rounded-lg mb-4"
            height="300"
            src="/placeholder.svg"
            style={{
              aspectRatio: "400/300",
              objectFit: "cover",
            }}
            width="400"
          />
          <h2 className="text-lg font-semibold mb-2 text-black">Your guess</h2>
          <p className="text-black no-margin">Astronauts playing chess</p>
        </div>
      </div>
      <div className="max-w-xs mx-auto">
        <div className="flex justify-between items-center mb-2">
          <h2 className="text-lg font-semibold text-black">Similarity score</h2>
          <span className="text-lg font-semibold text-black">80%</span>
        </div>
        <div className="w-full bg-gray-200 rounded-full h-2.5 mb-4">
          <div
            className="bg-green-500 h-2.5 rounded-full"
            style={{
              width: "80%",
            }}
          />
        </div>
        <div className="flex gap-4">
          <Button className="w-full" variant="outline">
            Share on Twitter
          </Button>
          <Button className="w-full">Play again</Button>
        </div>
      </div>
    </div>
  )
}
